CREATE TABLE Users (
	userID VARCHAR(10) NOT NULL UNIQUE,
    userType VARCHAR(10),
    username VARCHAR(30) NOT NULL UNIQUE,
    password VARCHAR(30) NOT NULL,
    email VARCHAR(30),
    firstName VARCHAR(30),
    lastName VARCHAR(30),
    image VARCHAR(255),
    description VARCHAR(255),
    region VARCHAR(30),
    attribute0 VARCHAR(30),
    attribute1 VARCHAR(30),
    attribute2 VARCHAR(30)
);

INSERT INTO Users (UserID, userType, username, password, firstName, lastName)
VALUES
('136378', 'ngo', 'rmazzeo', 'pass1', 'Rudolph', 'Mazzeo'),
('172086', 'ngo', 'klandis', 'pass1', 'Kayce', 'Landis'),
('583609', 'consultant', 'nrich', 'pass1', 'Nichole', 'Rich'),
('297907', 'consultant', 'gdesouza', 'pass1', 'Gudrun', 'Desouza'),
('736605', 'volunteer', 'alopresti', 'pass1', 'Aretha', 'Lopresti'),
('456684', 'volunteer', 'rbarbagallo', 'pass1', 'Rico', 'Barbagallo'),
('329176', 'volunteer', 'arasmus', 'pass1', 'Avery', 'Rasmus'),
('927152', 'volunteer', 'mherzog', 'pass1', 'Madie', 'Herzog'),
('293447', 'volunteer', 'elabro', 'pass1', 'Eduardo', 'Albro'),
('568721', 'volunteer', 'wrieck', 'pass1', 'Winfred', 'Rieck');

ALTER TABLE Users DROP COLUMN userID;

ALTER TABLE Users ADD COLUMN attribute2 VARCHAR (30) AFTER attribute1;
ALTER TABLE Users ADD userID INT UNSIGNED NOT NULL AUTO_INCREMENT,
    ADD INDEX (userID);
ALTER TABLE Users 
MODIFY COLUMN userID INT UNSIGNED NOT NULL FIRST;


SELECT COLUMN_NAME, DATA_TYPE 
FROM INFORMATION_SCHEMA.COLUMNS 
WHERE TABLE_NAME = 'Users';

USE weserve;

SELECT * FROM Users;

SET SQL_SAFE_UPDATES = 0;

UPDATE Users
SET attribute2 = 'lgbt'
WHERE  (userID % 6) = 5;

TRUNCATE TABLE Users;

ALTER TABLE Projects DROP FOREIGN KEY Projects_ibfk_1;

INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("960882","ngo","QWIFML88","LIN71EES5RV","Vestibulum.ante@Aliquameratvolutpat.ca","Paul","Tanner","Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean eget magna. Suspendisse tristique","HA","mattis","purus"),("104106","consultant","MKTZXM60","GQY79NZL2XY","dictum.sapien@pedenonummyut.ca","Upton","Gonzales","Nullam ut nisi a odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim","Bur","quis,","Pellentesque"),("050087","volunteer","QKGPZZ76","VQH87ZLV0FU","ante.iaculis@Etiamlaoreetlibero.ca","Connor","Wood","habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed","Berlin","turpis","est."),("719252","consultant","VBIYSN49","JOY81LGA3GR","Duis.risus.odio@et.ca","Isaiah","Suarez","placerat eget, venenatis a, magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus","VII","sollicitudin","sodales"),("057236","volunteer","YZVLXX28","TLO13LAI8EM","vulputate@Fusce.ca","Demetria","Ramirez","viverra. Donec tempus, lorem fringilla ornare placerat, orci lacus vestibulum lorem, sit amet ultricies sem magna nec quam. Curabitur vel","Metropolitana de Santiago","elit","mus."),("870683","ngo","DDYTYB45","LJK94GBZ1MD","Vivamus@augueac.com","Noelani","Patrick","Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu.","Kay","magna","egestas."),("715557","consultant","PVQYGC00","GMN11RKD3IG","ornare@felispurus.net","Erasmus","Long","quis arcu vel quam dignissim pharetra. Nam ac nulla. In tincidunt congue turpis. In condimentum. Donec at arcu. Vestibulum ante","Alberta","iaculis,","leo."),("689575","ngo","OOSPAG64","JTI94VOC8IV","scelerisque.scelerisque.dui@estmollisnon.edu","Madeson","Conley","condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec tincidunt. Donec","California","dictum","congue."),("270103","volunteer","QYMEWL37","LSL26PSY3UV","nisi.magna@mauriseu.org","Lyle","Flowers","dapibus quam quis diam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Fusce aliquet magna","PA","cursus","libero"),("716843","consultant","FGVPQH54","QNM36ACW7CW","Phasellus@Integervulputate.org","Hammett","Wynn","Donec tempor, est ac mattis semper, dui lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce","łódzkie","eu,","orci");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("704293","consultant","HCOEMX73","DHC84JPP7OP","id@netuset.com","Remedios","Clark","turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Donec","RJ","lorem,","Nunc"),("439305","ngo","MHURMN12","IIJ75PVG2SC","et.tristique@Vivamusmolestie.edu","Mia","Mullins","libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus vulputate, nisi sem semper erat, in consectetuer ipsum nunc","Brecknockshire","dui","aliquam,"),("976623","volunteer","ANZMDF54","HMD99YPS1OC","mi@et.edu","Richard","Benson","dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh","Delta","sed","Pellentesque"),("341374","ngo","DBQZJE05","OTU26JXU9RN","lacus.Cras.interdum@utpellentesqueeget.edu","Ross","Rosales","nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus","Vienna","cursus","nec"),("586310","consultant","ATWQVK43","IYG91OAZ9NF","enim.nisl.elementum@sapienimperdietornare.co.uk","Shelley","Wise","Mauris molestie pharetra nibh. Aliquam ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu","Georgia","aliquet","Morbi"),("640809","consultant","XLZNRZ45","GEV31LTC7IE","Curabitur.ut@faucibus.ca","Leo","Huff","commodo hendrerit. Donec porttitor tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien,","Alberta","habitant","nunc."),("390253","ngo","MXNHMB96","YZB08QXR5OW","dui.augue.eu@inmagna.edu","Ian","Medina","ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus.","BA","sagittis","Donec"),("381515","volunteer","RLRWSS58","ZQF78PNC2YJ","quam.quis.diam@nasceturridiculusmus.edu","Justin","Barrera","diam vel arcu. Curabitur ut odio vel est tempor bibendum. Donec felis orci, adipiscing non, luctus sit amet, faucibus ut,","VII","tempus,","semper"),("346020","ngo","MLWKWU99","LWZ78DKU7JB","Maecenas@blanditenim.org","Rylee","Contreras","amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim","QC","odio.","sapien."),("629183","ngo","TLIHKZ06","GUK68BHA0UH","enim.consequat@nunc.net","Hunter","Booth","magna. Phasellus dolor elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed","U","Maecenas","velit");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("334666","consultant","VLVHDU23","POT12OBV5HP","velit.Quisque@blandit.co.uk","Wyatt","Lopez","faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis","Victoria","mi.","et"),("999768","consultant","XSDIJM69","TQM88JVG8NI","Cum@convallisante.ca","Dana","Joyce","sem egestas blandit. Nam nulla magna, malesuada vel, convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet","Valparaíso","odio","Integer"),("117616","ngo","CYIKFK36","QAK08TJX3MM","lacus.Quisque.imperdiet@quamquisdiam.edu","Maile","Rodriguez","eu nulla at sem molestie sodales. Mauris blandit enim consequat purus. Maecenas libero est, congue a, aliquet vel, vulputate eu,","WV","Integer","auctor,"),("169915","consultant","EDCNFM98","CFT73PLT5BD","ultricies@neceleifend.com","Lillian","Gilliam","Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut, molestie in, tempus eu, ligula. Aenean euismod mauris","NO","orci","ac,"),("377997","consultant","HNTHQM15","WZG02EZH3KC","magna@CuraePhasellusornare.ca","Austin","Love","dignissim lacus. Aliquam rutrum lorem ac risus. Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas","QC","et","tincidunt."),("260465","volunteer","WJKLOT55","TTZ21VVE8PI","Integer.in.magna@liberoMorbi.ca","Joel","Hodges","fames ac turpis egestas. Aliquam fringilla cursus purus. Nullam scelerisque neque sed sem egestas blandit. Nam nulla magna, malesuada vel,","WA","nascetur","Maecenas"),("030842","volunteer","NKDMLL67","YCC62YRT3LS","risus.at@nequeSedeget.com","Salvador","Mendez","scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus.","Koc","arcu.","malesuada"),("145463","volunteer","YXECQH33","RCT20GCR7PI","odio.Aliquam@Sedet.ca","Akeem","Baker","lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper. Duis cursus, diam at","Manisa","mi","Proin"),("228941","consultant","KNCBDT73","EFP56SGO7ZZ","elit@aliquetnecimperdiet.ca","Leonard","Burns","lorem ut aliquam iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et","San José","libero.","feugiat"),("512050","consultant","AGAJLZ69","XTU11ROA3MK","magna.sed@quislectus.co.uk","Lev","Wilcox","lectus rutrum urna, nec luctus felis purus ac tellus. Suspendisse sed dolor. Fusce mi lorem, vehicula et, rutrum eu, ultrices","Z.","mauris.","cubilia");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("556225","ngo","EZYDCU37","UZX88JLX9EI","eleifend.nec.malesuada@Vestibulumante.org","Leilani","Beach","sollicitudin commodo ipsum. Suspendisse non leo. Vivamus nibh dolor, nonummy ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam","Ontario","nibh.","vitae,"),("530909","ngo","CBCJIY27","UNG86DII0RB","sociis.natoque.penatibus@ante.ca","Cooper","Camacho","dui. Suspendisse ac metus vitae velit egestas lacinia. Sed congue, elit sed consequat auctor, nunc nulla vulputate dui, nec tempus","MA","sem","ligula."),("287158","volunteer","JEURDX84","OMP32HAZ9IT","faucibus.orci.luctus@lectuspede.edu","Hilda","Harmon","nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis","N.","pellentesque","rutrum."),("124471","consultant","AWGAES71","NVQ36ALJ9JP","imperdiet@nonlaciniaat.co.uk","Kelly","Reese","in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac","Adana","at,","mollis."),("214392","ngo","LMOHUN08","AYF23MSF9QF","pede.Suspendisse@estmauris.edu","Katelyn","Dickson","enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor nibh sit amet orci. Ut sagittis lobortis mauris. Suspendisse","ON","Nunc","semper"),("846527","ngo","BUBGNC71","SXP10DDC8HX","fringilla@consectetueradipiscingelit.ca","Germaine","Hayes","luctus. Curabitur egestas nunc sed libero. Proin sed turpis nec mauris blandit mattis. Cras eget nisi dictum augue malesuada malesuada.","AB","a","Suspendisse"),("841587","ngo","WQNWKW75","NEP74KYG4PF","tempor.erat@Etiam.com","Leilani","Sheppard","dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat","Minas Gerais","gravida","porta"),("339541","ngo","ESYVNW00","OAE85WDV0JO","eu.enim.Etiam@magnaDuis.net","Duncan","Patel","Nulla eget metus eu erat semper rutrum. Fusce dolor quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu","BA","in,","Proin"),("915651","ngo","HJYORO37","XMM28CDF4SX","sapien.Aenean@massalobortis.ca","Neve","Franco","libero et tristique pellentesque, tellus sem mollis dui, in sodales elit erat vitae risus. Duis a mi fringilla mi lacinia","Alabama","elit.","lacinia"),("799658","volunteer","MDOELT84","PFV78IPE8MC","Nullam@sitamet.com","Evelyn","Hester","cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.","Campania","placerat,","et");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("624504","volunteer","OMIOAH13","MMA83YMF6RQ","cubilia@ligulaAeneaneuismod.com","Odette","Joyce","viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer","Stockholms län","nec","urna."),("517409","volunteer","CVTFDB93","PXQ25ZZS5XR","purus.sapien@variusNamporttitor.edu","Blake","Cobb","nibh lacinia orci, consectetuer euismod est arcu ac orci. Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel","Quebec","sagittis","eget"),("440656","consultant","HTODVX37","BNZ72BOY0GC","neque.Morbi@Etiamimperdiet.org","Dai","Harrison","ligula. Aliquam erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque.","BA","Phasellus","pede."),("786445","consultant","MSTMMC81","XPN47YDR5PZ","neque.Nullam@ac.co.uk","Abdul","Mccoy","accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac","Namen","Phasellus","Proin"),("756784","volunteer","WCLMTH59","FYE20GHE4EF","dolor.quam@nisimagnased.edu","Perry","Gibson","scelerisque mollis. Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis diam. Pellentesque habitant morbi","SL","augue","Vestibulum"),("926413","ngo","DIQTOA79","APB39IFW9TU","turpis@adipiscingfringillaporttitor.com","Akeem","Brooks","sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent luctus.","Jönköpings län","fringilla,","Duis"),("975175","consultant","OQHPHL51","EEN74VLW1IE","aliquam.adipiscing@Phasellusinfelis.net","Cleo","Chang","iaculis, lacus pede sagittis augue, eu tempor erat neque non quam. Pellentesque habitant morbi tristique senectus et netus et malesuada","HB","leo,","dignissim."),("838269","ngo","JHGYKZ74","DKJ02YSJ6BS","quis.pede@vulputateveliteu.ca","Chastity","Lamb","Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque pellentesque massa lobortis ultrices. Vivamus rhoncus. Donec est. Nunc ullamcorper, velit","WE","montes,","feugiat"),("312257","ngo","PUDSFL15","CQH83IXS3JY","Quisque@orciconsectetuereuismod.com","Ashton","Greer","mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus","Bahia","nisi","a"),("010978","volunteer","YCJQXQ35","PRC49FGV3DU","metus@leoelementumsem.edu","Noble","Underwood","Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis placerat. Cras dictum ultricies ligula. Nullam","Saskatchewan","et","interdum.");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("243298","ngo","CSVKDH87","DJM45OOK3TD","ultrices@diam.com","Myles","Morales","cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna.","VB","pede.","ornare"),("600977","consultant","HCEIWO46","ISS41VTB5VP","tempus.mauris@neque.net","Elmo","Erickson","faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas. Duis ac arcu. Nunc mauris. Morbi non sapien molestie orci tincidunt","Imo","justo","vitae"),("216155","ngo","YXPPSE37","JID84MWK7JL","eu.erat@enimnec.org","Tobias","Crawford","tellus non magna. Nam ligula elit, pretium et, rutrum non, hendrerit id, ante. Nunc mauris sapien, cursus in, hendrerit consectetuer,","Mazowieckie","Phasellus","magna."),("963182","ngo","NXEZON84","XDE50AAI3AH","nulla.magna@semelitpharetra.edu","Lester","Torres","dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam nisl. Nulla eu neque","PR","malesuada","sit"),("803950","volunteer","LOKOVY05","NMB45FAY2HD","tortor.Nunc@estvitae.co.uk","Cain","Skinner","nisl sem, consequat nec, mollis vitae, posuere at, velit. Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed","OK","Donec","posuere"),("897628","consultant","ZGPXQB61","NYV66TOB6QW","hymenaeos@sedturpisnec.org","Noble","Hardin","Morbi metus. Vivamus euismod urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed diam lorem, auctor","QLD","Nunc","eget"),("387655","consultant","LWAQTI18","PWD80ZAU9KV","nisl@Aeneanegestas.com","Lyle","Turner","Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus convallis est, vitae sodales nisi magna sed","DS","aliquet","porttitor"),("634558","volunteer","XBZZTY97","ICK29EKC2WY","tellus.imperdiet@Utsagittis.net","Oprah","Maynard","fringilla purus mauris a nunc. In at pede. Cras vulputate velit eu sem. Pellentesque ut ipsum ac mi eleifend egestas.","LA","in","Vivamus"),("980289","ngo","WCSOPM54","AEE05OIV3IC","consectetuer.mauris@utodio.co.uk","Macaulay","Howard","mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis odio. Nam interdum enim non nisi. Aenean eget metus. In nec orci.","Connecticut","Cras","Curabitur"),("533554","consultant","WPWZBX35","BLQ64DZG9MG","Integer.eu@sem.com","Alice","Sherman","mauris sagittis placerat. Cras dictum ultricies ligula. Nullam enim. Sed nulla ante, iaculis nec, eleifend non, dapibus rutrum, justo. Praesent","HB","eleifend","et");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("135606","volunteer","AGTSJD87","VLI78OLL6NE","nibh.Aliquam.ornare@Nullaegetmetus.co.uk","Baker","Nielsen","egestas, urna justo faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero.","Connacht","sagittis","ultrices"),("353089","volunteer","HJVLGA85","JEV47AYJ7EI","ornare.egestas.ligula@Pellentesque.net","Haley","Watts","Sed id risus quis diam luctus lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos.","Emilia-Romagna","semper","diam"),("245996","consultant","MFBCOP08","PNV78SIB2HR","Aenean.gravida@Donecelementumlorem.co.uk","Tallulah","Clemons","id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Proin vel nisl. Quisque","Kon","ullamcorper","gravida."),("896598","volunteer","MSUPPK00","RNB55PYV4MK","ipsum.ac.mi@In.net","Eleanor","Cotton","massa. Mauris vestibulum, neque sed dictum eleifend, nunc risus varius orci, in consequat enim diam vel arcu. Curabitur ut odio","UP","montes,","vitae"),("742237","volunteer","SGMKHP83","DBH87YOR5ED","cursus.vestibulum@massa.org","Lev","Patel","cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada ut, sem. Nulla interdum. Curabitur dictum. Phasellus in felis. Nulla tempor","Haute-Normandie","neque","egestas"),("096892","volunteer","IIVIXD36","XNE49MLB7FG","lorem.lorem.luctus@Nunclaoreet.co.uk","Anastasia","Hendrix","Phasellus vitae mauris sit amet lorem semper auctor. Mauris vel turpis. Aliquam adipiscing lobortis risus. In mi pede, nonummy ut,","NI","Donec","ipsum"),("314507","volunteer","ECPSVJ82","WDN20LFH4BN","cursus.luctus.ipsum@Nuncmauris.edu","Anthony","Clemons","enim. Nunc ut erat. Sed nunc est, mollis non, cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget","Västra Götalands län","fermentum","Donec"),("640763","ngo","PQBUNP87","XPA24XYA3BR","a@aceleifend.edu","Gage","Pitts","Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non,","Bahia","semper","vitae"),("707182","volunteer","FMZSWQ51","ITS86JWT3YH","sagittis@Donecfeugiatmetus.co.uk","Colton","Lawson","erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh. Phasellus nulla. Integer vulputate, risus a ultricies adipiscing, enim mi tempor lorem,","Wie","primis","elementum"),("422649","ngo","KSDHTU46","KDT57JBW3LE","ullamcorper.nisl.arcu@antelectus.edu","Kuame","Ferrell","faucibus lectus, a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer in magna.","CV","orci","elementum");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("479780","volunteer","KBTYAO67","YTB65KUM6UP","molestie.tellus.Aenean@nequevenenatislacus.co.uk","Beck","Rivers","Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi. Cum sociis natoque penatibus et magnis dis parturient montes,","L","consectetuer","fringilla"),("620709","volunteer","NYRRFV78","FLK09EDT5DE","ac@varius.edu","Melvin","Hurley","eu enim. Etiam imperdiet dictum magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis, magna tellus faucibus","KT","inceptos","viverra."),("766062","consultant","HYMXFU60","PIC64NSR4IZ","convallis.est.vitae@rutrumjusto.edu","Tanner","Rosario","consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus. Nunc ac sem","RA","varius.","Integer"),("498726","volunteer","LLDPHI15","BXD28NKO4UR","Aliquam.tincidunt.nunc@neceleifend.co.uk","Isabella","Tran","cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo tincidunt nibh.","AB","vulputate","libero."),("827511","volunteer","FAVFBU15","KWU60KCB2XU","magnis.dis.parturient@rutrum.edu","Yoshi","Koch","mi eleifend egestas. Sed pharetra, felis eget varius ultrices, mauris ipsum porta elit, a feugiat tellus lorem eu metus. In","NI","placerat.","varius"),("810628","consultant","KWDTGS17","TIS80XNO7XY","Morbi.quis.urna@facilisislorem.net","Alfonso","Welch","sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor vitae, aliquet","Pará","luctus","Nam"),("317201","volunteer","IQZSFO79","OOC65BCT2UI","non@Nuncmauris.ca","Halee","Casey","Sed diam lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer urna. Vivamus molestie dapibus ligula.","Florida","nisl","euismod"),("137875","volunteer","YHJQUD94","KWW31BPV1IV","pede.Suspendisse.dui@quamCurabitur.ca","Leonard","Hunt","Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum. Donec sollicitudin adipiscing ligula. Aenean gravida nunc sed pede. Cum","BE","cubilia","auctor,"),("074382","consultant","ITTNDX24","NGT35QCQ8HZ","at.libero@nibhdolornonummy.edu","Lillian","Powers","tellus faucibus leo, in lobortis tellus justo sit amet nulla. Donec non justo. Proin non massa non ante bibendum ullamcorper.","NSW","Proin","mollis"),("733585","consultant","IGNPXO40","NZZ05OET5PI","parturient.montes.nascetur@vitae.net","Wayne","Carroll","fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero. Proin mi. Aliquam gravida","LX","Curabitur","eu,");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("857257","ngo","YSRRKH54","NMY72FKU3UA","Nunc.ullamcorper@Nuncmauris.net","Micah","Wilkinson","magna. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Etiam laoreet, libero et tristique pellentesque, tellus sem mollis dui, in","Västra Götalands län","non","convallis"),("241075","consultant","MJTRCE82","ZJC13GGQ1QO","Morbi.non.sapien@Fuscealiquam.net","Hedda","William","amet massa. Quisque porttitor eros nec tellus. Nunc lectus pede, ultrices a, auctor non, feugiat nec, diam. Duis mi enim,","Sokoto","eget","mattis"),("801296","volunteer","JDGQVD39","ZGY70COF5AO","Nullam.ut@nequepellentesquemassa.ca","Derek","Maxwell","Cras lorem lorem, luctus ut, pellentesque eget, dictum placerat, augue. Sed molestie. Sed id risus quis diam luctus lobortis. Class","IX","gravida","massa."),("721932","volunteer","RPXIJV38","BKS61KUK2LD","Duis.ac.arcu@maurisIntegersem.ca","Sonya","Ayala","per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula. Pellentesque tincidunt tempus risus. Donec egestas.","Île-de-France","elit,","malesuada"),("673500","ngo","YBYUKI96","QAZ38GKX5WD","tincidunt@Aliquam.edu","Rajah","Stone","lobortis. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam vel sapien imperdiet","MI","mauris","ridiculus"),("777557","consultant","DGTXNT07","PGX00SAN3IR","Lorem.ipsum.dolor@Suspendisse.ca","Basia","Weber","Duis cursus, diam at pretium aliquet, metus urna convallis erat, eget tincidunt dui augue eu tellus. Phasellus elit pede, malesuada","Ada","enim","convallis"),("944263","ngo","RIZATM68","CYK41TIF2JN","faucibus@inlobortistellus.co.uk","Raphael","Ryan","natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim magna a tortor. Nunc commodo auctor velit. Aliquam","NÖ.","lobortis","consequat"),("805054","consultant","VRSOQZ90","LCL03SQC3VK","nec.ligula.consectetuer@id.edu","Vaughan","Harrison","ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non","UP","molestie","viverra."),("234405","consultant","DSKRNN95","PZH50UOK5KC","quam.elementum@fringilla.org","Macon","Garrison","lorem, vehicula et, rutrum eu, ultrices sit amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi.","Vienna","purus","Nunc"),("241513","consultant","WEDFML82","PVM66JQQ0NT","Aliquam@urna.net","Wynter","Clarke","convallis in, cursus et, eros. Proin ultrices. Duis volutpat nunc sit amet metus. Aliquam erat volutpat. Nulla facilisis. Suspendisse commodo","Alberta","pellentesque","eu,");
INSERT INTO `Users` (`userID`,`userType`,`username`,`password`,`email`,`firstName`,`lastName`,`description`,`region`,`attribute0`,`attribute1`) VALUES ("618814","ngo","EAZBGN31","CJT20VKU6JH","lobortis@amalesuadaid.com","Elijah","Holloway","vestibulum. Mauris magna. Duis dignissim tempor arcu. Vestibulum ut eros non enim commodo hendrerit. Donec porttitor tellus non magna. Nam","PA","ridiculus","Cras"),("771102","ngo","UYLQYP33","VZG82LMC6UZ","suscipit.est.ac@Nullatemporaugue.ca","Beck","Barrera","nascetur ridiculus mus. Proin vel nisl. Quisque fringilla euismod enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis","OK","accumsan","mi"),("654820","ngo","HVEFMW59","ZYN64RMA1RB","sit.amet.consectetuer@Quisquetincidunt.com","Hyacinth","Bryant","sem ut dolor dapibus gravida. Aliquam tincidunt, nunc ac mattis ornare, lectus ante dictum mi, ac mattis velit justo nec","LAZ","commodo","neque."),("423102","volunteer","FJOMUT21","VYZ82ZOW9EJ","sem@ut.ca","Burke","Frank","Cras eu tellus eu augue porttitor interdum. Sed auctor odio a purus. Duis elementum, dui quis accumsan convallis, ante lectus","North Island","eu","Aliquam"),("640428","ngo","AUYCZF60","KIY59NLW4AX","mauris.rhoncus.id@fringillapurusmauris.co.uk","Wallace","Holland","ornare, libero at auctor ullamcorper, nisl arcu iaculis enim, sit amet ornare lectus justo eu arcu. Morbi sit amet massa.","Ohio","malesuada","quis"),("040194","consultant","OBXKKH70","EIF14HHV5NU","suscipit.est@utmi.net","Moses","Guerrero","neque tellus, imperdiet non, vestibulum nec, euismod in, dolor. Fusce feugiat. Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aliquam","AN","ornare,","eu"),("559643","ngo","LVUWOK54","EAW18KWV2NX","bibendum.sed.est@lobortis.edu","Gillian","Tyler","at, iaculis quis, pede. Praesent eu dui. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Aenean","BU","fringilla.","mattis."),("677155","consultant","YQXQON59","BQL79OHW4PQ","a.purus@ante.com","Omar","Kaufman","aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum cursus. Nunc mauris elit, dictum eu, eleifend nec, malesuada","Madrid","ante","ligula."),("018575","volunteer","BENJZN49","HSL59VNS6RK","scelerisque.neque.sed@eu.com","Owen","Beck","aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae purus","Ulster","libero","cursus"),("967723","consultant","LOFKSX57","FAE04BOC7RL","eu.odio@amet.com","Bradley","Barton","elit, pellentesque a, facilisis non, bibendum sed, est. Nunc laoreet lectus quis massa. Mauris vestibulum, neque sed dictum eleifend, nunc","Benue","ac,","at,");

SELECT userID
FROM Users
WHERE userType = 'ngo';